
# Python Verification for Join Operator Theorems
# Generated by ILDA Iteration 10
# Date: 2026-03-06

import numpy as np
from scipy.integrate import solve_ivp

def test_metric_tension_nonnegative():
    print("Testing Metric Tension Non-Negativity...")
    
    def P_A(x):
        return 1 / (1 + np.exp(-x))
    
    def P_B(x):
        return 1 / (1 + np.exp(-(x-1)))
    
    kappa = 0.5
    x_values = np.linspace(-5, 5, 100)
    
    for x in x_values:
        P_A_k = P_A(kappa)
        P_B_k = P_B(kappa)
        
        if P_A_k == 0 and P_B_k == 0:
            metric_tension = 0
        elif P_B_k == 0:
            metric_tension = np.inf
        elif P_A_k == 0:
            metric_tension = 0
        else:
            metric_tension = P_A_k * np.log(P_A_k / P_B_k)
        
        assert metric_tension >= 0 or metric_tension == np.inf
    
    print("  PASSED: Metric tension is non-negative")

def test_lyapunov_convergence():
    print("Testing Lyapunov Convergence to Zero...")
    
    Gamma0 = 1.0
    lambda_val = 0.618  # Golden ratio
    
    # Test convergence for large t
    t_values = np.linspace(0, 50, 100)
    Gamma_values = Gamma0 * np.exp(-lambda_val * t_values)
    
    # Check that values approach zero
    assert Gamma_values[-1] < 1e-10
    assert np.all(np.diff(Gamma_values) <= 0)  # Monotonically decreasing
    
    print("  PASSED: Lyapunov function converges to zero")

def test_grokking_improvement():
    print("Testing Grokking Improvement...")
    
    Gamma0 = 1.0
    lambda_val = 0.618
    
    # Calculate time needed for improvement
    T_needed = np.log(100 * Gamma0) / lambda_val
    
    # Verify improvement at T_needed
    Gamma_T = Gamma0 * np.exp(-lambda_val * T_needed)
    I_T = 1 / Gamma_T
    
    assert I_T >= 100 * 0.99  # Allow small numerical error
    
    # Also verify for larger T
    T_larger = T_needed * 2
    Gamma_T2 = Gamma0 * np.exp(-lambda_val * T_larger)
    I_T2 = 1 / Gamma_T2
    
    assert I_T2 > I_T  # Improvement continues to increase
    
    print(f"  PASSED: improvement achieved at t = {T_needed:.2f}")
    print(f"  Improvement at t = {T_needed:.2f}: {I_T:.2f}x")

def test_lyapunov_decreasing():
    print("Testing Lyapunov Function Monotonicity...")
    
    Gamma0 = 1.0
    lambda_val = 0.618
    
    t_values = np.linspace(0, 20, 200)
    Gamma_values = Gamma0 * np.exp(-lambda_val * t_values)
    
    # Check monotonic decrease
    for i in range(len(t_values) - 1):
        assert Gamma_values[i+1] <= Gamma_values[i] + 1e-10
    
    print("  PASSED: Lyapunov function is monotonically decreasing")

def test_improvement_formula():
    print("Testing Improvement Metric Formula...")
    
    Gamma0 = 1.0
    lambda_val = 0.618
    
    for t in np.linspace(0, 10, 20):
        Gamma_t = Gamma0 * np.exp(-lambda_val * t)
        I_t = 1 / (Gamma_t + 1e-10)
        
        # Check formula
        I_formula = np.exp(lambda_val * t) / Gamma0
        assert np.isclose(I_t, I_formula, rtol=1e-5)
    
    print("  PASSED: Improvement metric formula verified")

def run_all_tests():
    print("="*80)
    print("JOIN OPERATOR THEOREMS: PYTHON VERIFICATION")
    print("="*80)
    print()
    
    tests = [
        test_metric_tension_nonnegative,
        test_lyapunov_convergence,
        test_grokking_improvement,
        test_lyapunov_decreasing,
        test_improvement_formula
    ]
    
    passed = 0
    failed = 0
    
    for test in tests:
        try:
            test()
            passed += 1
        except AssertionError as e:
            print(f"  FAILED: {e}")
            failed += 1
        except Exception as e:
            print(f"  ERROR: {e}")
            failed += 1
    
    print()
    print("="*80)
    print("VERIFICATION SUMMARY")
    print("="*80)
    print(f"Total tests: {len(tests)}")
    print(f"Passed: {passed}")
    print(f"Failed: {failed}")
    print(f"Success rate: {passed / len(tests) * 100:.1f}%")
    
    return passed == len(tests)

if __name__ == "__main__":
    success = run_all_tests()
    exit(0 if success else 1)
