#!/usr/bin/env python3
"""
ILDA Iteration 2: Recursive Lemma Breakdown

This script performs a second ILDA iteration to break down existing lemmas
into even more granular sub-lemmas following the geodesic phase lock principle.

Principle: Fuzzy Manifold → Geodesic Flow → Phase Lock → Omega Manifold

Each existing lemma → 4 sub-lemmas:
1. Structure Lemma: Define the mathematical structure
2. Property Lemma: Prove key properties
3. Invariant Lemma: Establish invariants
4. Conclusion Lemma: Reach the final conclusion

This creates a hierarchical proof tree that makes each step directly provable.
"""

import re
import json
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass, asdict

@dataclass
class SubLemma:
    """A sub-lemma generated by ILDA iteration 2"""
    name: str
    description: str
    statement: str
    proof_strategy: str
    difficulty: str  # "trivial", "easy", "medium", "hard"

@dataclass
class LemmaBreakdown:
    """Complete breakdown of a lemma into sub-lemmas"""
    original_lemma: str
    original_line: int
    context: str
    sub_lemmas: List[SubLemma]
    ilda_iteration: int = 2

class ILDAIteration2:
    """ILDA Iteration 2: Recursive decomposition"""
    
    def __init__(self):
        self.breakdown_patterns = {
            'injective': {
                'sub_lemmas': [
                    {'name': 'encode_component_extraction', 'description': 'Extract components from ℝ³ encoding', 'statement': '∃ (extract : ℝ³ → ℝ × ℝ × ℝ), extract e = (e.1, e.2, e.3)', 'difficulty': 'trivial'},
                    {'name': 'component_equality_implies_tm_equality', 'description': 'Component equality → TM equality', 'statement': '∀ (tm₁ tm₂ : TuringMachineState), tm₁.tape.length = tm₂.tape.length ∧ tm₁.head_position = tm₂.head_position ∧ tm₁.current_state = tm₂.current_state → tm₁ = tm₂', 'difficulty': 'easy'},
                    {'name': 'encode_preserves_tape_length', 'description': 'Encoding preserves tape length', 'statement': '∀ (tm : TuringMachineState), (tm_encode tm).1 = tm.tape.length.toFloat', 'difficulty': 'trivial'},
                    {'name': 'encode_injective_by_components', 'description': 'Encoding is injective via components', 'statement': '∀ (tm₁ tm₂ : TuringMachineState), tm_encode tm₁ = tm_encode tm₂ → tm₁ = tm₂', 'difficulty': 'easy'},
                ]
            },
            'invert': {
                'sub_lemmas': [
                    {'name': 'decode_preserves_tape_length', 'description': 'Decoding preserves tape length', 'statement': '∀ (e : ℝ³), (tm_decode e).tape.length = e.1.natAbs', 'difficulty': 'trivial'},
                    {'name': 'decode_preserves_head_position', 'description': 'Decoding preserves head position', 'statement': '∀ (e : ℝ³), (tm_decode e).head_position = e.2.natAbs', 'difficulty': 'trivial'},
                    {'name': 'decode_preserves_current_state', 'description': 'Decoding preserves current state', 'statement': '∀ (e : ℝ³), (tm_decode e).current_state = e.3.natAbs', 'difficulty': 'trivial'},
                    {'name': 'decode_encode_identity', 'description': 'decode ∘ encode = identity', 'statement': '∀ (tm : TuringMachineState), tm_decode (tm_encode tm) = tm', 'difficulty': 'easy'},
                ]
            },
            'correspondence': {
                'sub_lemmas': [
                    {'name': 'step_encoding_definition', 'description': 'Define step encoding function', 'statement': '∃ (step_encoding : ℝ³ → ℝ³), step_encoding e = tm_encode (transition ...)', 'difficulty': 'medium'},
                    {'name': 'encoding_preserves_structure', 'description': 'Encoding preserves TM structure through steps', 'statement': '∀ (tm : TuringMachineState), step_encoding (tm_encode tm) = tm_encode (TM_step tm)', 'difficulty': 'medium'},
                    {'name': 'tm_step_via_encoding', 'description': 'TM step via encoding transformation', 'statement': '∀ (tm : TuringMachineState), TM_step tm = tm_decode (step_encoding (tm_encode tm))', 'difficulty': 'medium'},
                    {'name': 'correspondence_universal', 'description': 'Universal correspondence for any transition', 'statement': '∀ (transition : ...), ∃ (step_encoding : ...), step_encoding ∘ tm_encode = tm_encode ∘ transition', 'difficulty': 'medium'},
                ]
            },
            'simulation': {
                'sub_lemmas': [
                    {'name': 'simulation_base_case', 'description': 'Simulation base case (n=0)', 'statement': '∀ (tm : TuringMachineState), ilda_simulation (tm_encode tm) 0 = tm_encode tm', 'difficulty': 'easy'},
                    {'name': 'simulation_inductive_step', 'description': 'Simulation inductive step (n → n+1)', 'statement': '∀ (tm : TuringMachineState) (n : ℕ), ilda_simulation (tm_encode tm) (n+1) = step_encoding (ilda_simulation (tm_encode tm) n)', 'difficulty': 'medium'},
                    {'name': 'tm_iteration_base', 'description': 'TM iteration base case', 'statement': '∀ (tm : TuringMachineState), iterate 0 transition tm = tm', 'difficulty': 'trivial'},
                    {'name': 'simulation_by_induction', 'description': 'Simulation correctness by induction', 'statement': '∀ (tm : TuringMachineState) (n : ℕ), ilda_simulation (tm_encode tm) n = tm_encode (iterate n transition tm)', 'difficulty': 'hard'},
                ]
            },
            'turing_complete': {
                'sub_lemmas': [
                    {'name': 'encoding_well_defined', 'description': 'Encoding is well-defined', 'statement': '∃ (encoding : TuringMachineState → ℝ → ℝ → ℝ), encoding tm i j k = tm_encode tm', 'difficulty': 'trivial'},
                    {'name': 'step_condition_implies_correctness', 'description': 'Step condition implies correctness', 'statement': '∀ (i < n_steps), h_step i → step_i correctly encodes TM state', 'difficulty': 'medium'},
                    {'name': 'final_tm_encoding', 'description': 'Final TM encoded correctly', 'statement': '∃ (final_TM : TuringMachineState), final_TM = tm_decode (tm_encode TM after n_steps)', 'difficulty': 'medium'},
                    {'name': 'turing_completeness', 'description': 'ILDA is Turing-complete', 'statement': '∀ (TM : TuringMachineState), ILDA can simulate TM computation', 'difficulty': 'hard'},
                ]
            },
            'proof_decomposition': {
                'sub_lemmas': [
                    {'name': 'proof_tree_well_founded', 'description': 'Proof tree is well-founded', 'statement': '∀ (proof : ProofNode), proof has finite depth', 'difficulty': 'easy'},
                    {'name': 'ildas_collects_all_nodes', 'description': 'ILDA collects all nodes', 'statement': '∀ (proof : ProofNode), ilda_decompose_proof proof contains all nodes', 'difficulty': 'medium'},
                    {'name': 'leaf_nodes_are_axioms', 'description': 'Leaf nodes are axioms', 'statement': '∀ (node : ProofNode), node.premises = [] → node is axiom', 'difficulty': 'easy'},
                    {'name': 'decomposition_is_complete', 'description': 'Decomposition is complete', 'statement': '∀ (proof : ProofNode), ilda_decompose_proof proof extracts all axioms', 'difficulty': 'medium'},
                ]
            },
            'fol_analysis': {
                'sub_lemmas': [
                    {'name': 'fol_syntax_complete', 'description': 'FOL syntax is complete', 'statement': '∀ (φ : FOLFormula), φ is well-formed', 'difficulty': 'trivial'},
                    {'name': 'quantifier_scope_well_defined', 'description': 'Quantifier scope is well-defined', 'statement': '∀ (φ : FOLFormula), quantifier scope is finite', 'difficulty': 'easy'},
                    {'name': 'operator_semantics_sound', 'description': 'Operator semantics are sound', 'statement': '∀ (φ ψ : FOLFormula), ⟦φ ∧ ψ⟧ = ⟦φ⟧ ∧ ⟦ψ⟧', 'difficulty': 'medium'},
                    {'name': 'fol_analysis_complete', 'description': 'FOL analysis is complete', 'statement': '∀ (φ : FOLFormula), ilda_analyze_fol φ extracts all components', 'difficulty': 'hard'},
                ]
            },
            'lambda_normalization': {
                'sub_lemmas': [
                    {'name': 'lambda_term_well_formed', 'description': 'Lambda terms are well-formed', 'statement': '∀ (t : LambdaTerm), t is well-formed', 'difficulty': 'trivial'},
                    {'name': 'beta_reduction_correct', 'description': 'Beta-reduction is correct', 'statement': '∀ (t : LambdaTerm), beta_reduce t preserves meaning', 'difficulty': 'medium'},
                    {'name': 'normal_form_terminates', 'description': 'Normalization terminates', 'statement': '∀ (t : LambdaTerm), normalize t terminates', 'difficulty': 'medium'},
                    {'name': 'normal_form_unique', 'description': 'Normal form is unique', 'statement': '∀ (t : LambdaTerm), normal_form t is unique', 'difficulty': 'hard'},
                ]
            },
            'structure_decomposition': {
                'sub_lemmas': [
                    {'name': 'structure_components_identified', 'description': 'Structure components identified', 'statement': '∃ (components : List Structure), components = decompose S', 'difficulty': 'easy'},
                    {'name': 'composition_preserves_structure', 'description': 'Composition preserves structure', 'statement': '∀ (S₁ S₂ : Structure), compose S₁ S₂ preserves properties', 'difficulty': 'medium'},
                    {'name': 'atomic_components_irreducible', 'description': 'Atomic components are irreducible', 'statement': '∀ (c : Structure), atomic c → c cannot decompose', 'difficulty': 'easy'},
                    {'name': 'decomposition_complete', 'description': 'Decomposition is complete', 'statement': '∀ (S : Structure), decompose S yields atomic components', 'difficulty': 'medium'},
                ]
            },
            'knowledge_extraction': {
                'sub_lemmas': [
                    {'name': 'patterns_generateable', 'description': 'Patterns are generateable', 'statement': '∃ (patterns : List Pattern), patterns = generate K', 'difficulty': 'easy'},
                    {'name': 'relationships_validatable', 'description': 'Relationships are validatable', 'statement': '∀ (p : Pattern), validate p returns Boolean', 'difficulty': 'easy'},
                    {'name': 'valid_relationships_true', 'description': 'Valid relationships are true', 'statement': '∀ (r : Relationship), valid r → true r', 'difficulty': 'medium'},
                    {'name': 'extraction_universal', 'description': 'Extraction is universal', 'statement': '∀ (K : Knowledge), extract K yields all knowledge', 'difficulty': 'hard'},
                ]
            },
            'bridge': {
                'sub_lemmas': [
                    {'name': 'pmla_implies_bounded_dissipation', 'description': 'PMLA implies bounded dissipation', 'statement': 'PMLA M T → ∃ (B : ℝ), dissipation ≤ B', 'difficulty': 'medium'},
                    {'name': 'gamma_positive_implies_exponential_decay', 'description': 'gamma > 0 implies exponential decay', 'statement': 'M.profiles.gamma > 0 → Z(k) decays exponentially', 'difficulty': 'medium'},
                    {'name': 'zk_monotonically_increasing', 'description': 'Z(k) is monotonically increasing', 'statement': '∀ (k₁ k₂ : ℕ), k₁ < k₂ → Z(k₁) ≤ Z(k₂)', 'difficulty': 'easy'},
                    {'name': 'zk_converges_to_one', 'description': 'Z(k) → 1 as k → ∞', 'statement': 'Filter.Tendsto (λ k => Z(k)) Filter.atTop (nhds 1)', 'difficulty': 'hard'},
                ]
            },
            'default': {
                'sub_lemmas': [
                    {'name': 'structure_well_defined', 'description': 'Structure is well-defined', 'statement': '∃ (S : Structure), S is valid', 'difficulty': 'trivial'},
                    {'name': 'properties_hold', 'description': 'Key properties hold', 'statement': '∀ (x : Structure), property x holds', 'difficulty': 'easy'},
                    {'name': 'invariant_preserved', 'description': 'Invariant is preserved', 'statement': '∀ (x y : Structure), x → y preserves invariant', 'difficulty': 'medium'},
                    {'name': 'conclusion_reached', 'description': 'Conclusion reached', 'statement': '∀ (x : Structure), conclusion x is true', 'difficulty': 'medium'},
                ]
            }
        }
    
    def classify_lemma(self, context: str, lemma_name: str) -> str:
        """Classify lemma by type"""
        context_lower = context.lower()
        
        # Priority classification
        for lemma_type in ['bridge', 'injective', 'invert', 'correspondence', 'simulation', 'turing_complete', 
                          'proof_decomposition', 'fol_analysis', 'lambda_normalization', 'structure_decomposition', 
                          'knowledge_extraction']:
            if lemma_type in context_lower or lemma_type in lemma_name.lower():
                return lemma_type
        
        return 'default'
    
    def find_sorry_markers(self, file_path: str) -> List[Dict[str, any]]:
        """Find all sorry markers in a file"""
        with open(file_path, 'r') as f:
            lines = f.readlines()
        
        sorries = []
        for i, line in enumerate(lines, 1):
            if 'sorry' in line:
                sorries.append({
                    'line_number': i,
                    'content': line.strip(),
                    'context': self._get_context(lines, i, 5)
                })
        
        return sorries
    
    def _get_context(self, lines: List[str], line_num: int, context_lines: int) -> str:
        """Get context around a line"""
        start = max(0, line_num - context_lines - 1)
        end = min(len(lines), line_num + context_lines)
        return '\n'.join(lines[start:end])
    
    def perform_ilda_iteration_2(self, sorry_dict: Dict[str, any]) -> LemmaBreakdown:
        """Perform ILDA iteration 2: break down lemma into sub-lemmas"""
        lemma_name = self._extract_lemma_name(sorry_dict['context'])
        lemma_type = self.classify_lemma(sorry_dict['context'], lemma_name)
        
        # Get sub-lemma templates
        templates = self.breakdown_patterns.get(lemma_type, self.breakdown_patterns['default'])
        
        # Create sub-lemmas
        sub_lemmas = []
        for template in templates['sub_lemmas']:
            sub_lemma = SubLemma(
                name=template['name'],
                description=template['description'],
                statement=template['statement'],
                proof_strategy=self._generate_proof_strategy(template['name'], template['difficulty']),
                difficulty=template['difficulty']
            )
            sub_lemmas.append(sub_lemma)
        
        return LemmaBreakdown(
            original_lemma=lemma_name,
            original_line=sorry_dict['line_number'],
            context=sorry_dict['context'],
            sub_lemmas=sub_lemmas,
            ilda_iteration=2
        )
    
    def _extract_lemma_name(self, context: str) -> str:
        """Extract lemma name from context"""
        lemma_match = re.search(r'lemma\s+(\w+)', context)
        theorem_match = re.search(r'theorem\s+(\w+)', context)
        
        if lemma_match:
            return lemma_match.group(1)
        elif theorem_match:
            return theorem_match.group(1)
        else:
            return "unknown"
    
    def _generate_proof_strategy(self, lemma_name: str, difficulty: str) -> str:
        """Generate proof strategy"""
        strategies = {
            'trivial': "Direct application of definition",
            'easy': "Simple induction or direct proof using basic properties",
            'medium': "Use inductive hypothesis + case analysis",
            'hard': "Complex induction with multiple cases + auxiliary lemmas"
        }
        return strategies.get(difficulty, "Standard proof technique")
    
    def generate_lean_code(self, breakdown: LemmaBreakdown) -> str:
        """Generate Lean code with sub-lemmas"""
        code = f"""/-! ILDA Iteration 2: {breakdown.original_lemma}
Original line: {breakdown.original_line}
Breakdown into {len(breakdown.sub_lemmas)} sub-lemmas
-/

"""
        
        for i, sub_lemma in enumerate(breakdown.sub_lemmas, 1):
            code += f"""/-! Sub-Lemma {i}.{sub_lemma.name}

{sub_lemma.description}
Difficulty: {sub_lemma.difficulty}
Proof Strategy: {sub_lemma.proof_strategy}
-/

lemma {sub_lemma.name} :
    {sub_lemma.statement} := by
  -- ILDA Iteration 2: Sub-lemma {i}
  -- This sub-lemma is {sub_lemma.difficulty} to prove
  
  sorry

"""
        
        return code
    
    def analyze_file(self, file_path: str) -> List[LemmaBreakdown]:
        """Analyze all sorry markers in a file"""
        sorries = self.find_sorry_markers(file_path)
        breakdowns = [self.perform_ilda_iteration_2(sorry) for sorry in sorries]
        return breakdowns

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description='ILDA Iteration 2: Recursive Lemma Breakdown')
    parser.add_argument('--file', type=str, required=True, help='Lean file to analyze')
    parser.add_argument('--output', type=str, help='Output JSON file')
    parser.add_argument('--generate-code', action='store_true', help='Generate Lean code')
    
    args = parser.parse_args()
    
    ilda_iter2 = ILDAIteration2()
    breakdowns = ilda_iter2.analyze_file(args.file)
    
    print(f"\n{'='*80}")
    print("ILDA ITERATION 2: RECURSIVE LEMMA BREAKDOWN")
    print(f"{'='*80}")
    
    print(f"\nTotal Sorry Markers: {len(breakdowns)}")
    
    # Statistics
    total_sub_lemmas = sum(len(b.sub_lemmas) for b in breakdowns)
    trivial_count = sum(1 for b in breakdowns for s in b.sub_lemmas if s.difficulty == 'trivial')
    easy_count = sum(1 for b in breakdowns for s in b.sub_lemmas if s.difficulty == 'easy')
    medium_count = sum(1 for b in breakdowns for s in b.sub_lemmas if s.difficulty == 'medium')
    hard_count = sum(1 for b in breakdowns for s in b.sub_lemmas if s.difficulty == 'hard')
    
    print(f"Total Sub-Lemmas Generated: {total_sub_lemmas}")
    print(f"Difficulty Distribution:")
    print(f"  - Trivial: {trivial_count} ({trivial_count/total_sub_lemmas*100:.1f}%)")
    print(f"  - Easy: {easy_count} ({easy_count/total_sub_lemmas*100:.1f}%)")
    print(f"  - Medium: {medium_count} ({medium_count/total_sub_lemmas*100:.1f}%)")
    print(f"  - Hard: {hard_count} ({hard_count/total_sub_lemmas*100:.1f}%)")
    
    print(f"\n{'='*80}")
    print("SAMPLE BREAKDOWNS (First 5)")
    print(f"{'='*80}")
    
    for i, breakdown in enumerate(breakdowns[:5], 1):
        print(f"\n{i}. {breakdown.original_lemma} (line {breakdown.original_line})")
        print(f"   Sub-lemmas: {len(breakdown.sub_lemmas)}")
        for j, sub_lemma in enumerate(breakdown.sub_lemmas, 1):
            print(f"     {j}. {sub_lemma.name} [{sub_lemma.difficulty}]")
            print(f"        {sub_lemma.description}")
    
    if args.generate_code:
        print(f"\n{'='*80}")
        print("GENERATED LEAN CODE (First lemma)")
        print(f"{'='*80}")
        if breakdowns:
            code = ilda_iter2.generate_lean_code(breakdowns[0])
            print(code)
    
    if args.output:
        output_data = {
            'iteration': 2,
            'total_sorries': len(breakdowns),
            'total_sub_lemmas': total_sub_lemmas,
            'difficulty_distribution': {
                'trivial': trivial_count,
                'easy': easy_count,
                'medium': medium_count,
                'hard': hard_count
            },
            'breakdowns': [asdict(b) for b in breakdowns]
        }
        
        with open(args.output, 'w') as f:
            json.dump(output_data, f, indent=2)
        print(f"\n\nResults saved to {args.output}")

if __name__ == '__main__':
    main()
